networks:
  backend-network:
     external: true

services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - backend-network

  spring-boot-app:
    build: .
    container_name: spring_boot_container
    depends_on:
      - db
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      IMAGE_SERVICE_URL: ${IMAGE_SERVICE_URL}
    ports:
      - "8080:8080"
    networks:
      - backend-network

volumes:
  db_data: