services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_DB: ticket-booking-system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  spring-boot-app:
    build: .
    container_name: spring_boot_container
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/ticket-booking-system
      - DB_USERNAME=postgres
      - DB_PASSWORD=12345
    ports:
      - "8080:8080"

volumes:
  db_data: