apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: ticketbookingsystem-spring-boot-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgres-service:5432/ticket-booking-system
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: "12345"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092
            - name: IMAGE_SERVICE_URL
              value: http://image-service:8081/api/v1/images

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
